### PR TITLE
README.md file updated

### PR DESCRIPTION
**Pull request by angelotheman**
## Items added
- Man pages
- Branch names
- Motivation quote at the end.

This is a basic pull request test

### CODE REVIEW

**Comment by Benobbi** [comment]
I issued a git pull, but im still getting the old readme

**Comment by angelotheman** [comment]
I created this so that you review what I have done, then you can apply the reviewed or check to it.

When you're done, this PR(pull request) would be closed and then I would merge into the main.

**Review by Benobbi — CHANGES_REQUESTED** [review]
lets change Bennet Cobinnah to Bennett Cobbiah

**Comment by Benobbi** [comment]
I requested some changes. ive closed the pull request

**Comment by angelotheman** [comment]
I would make the changes. But please create your branch and add it up.

There would always be a pull request before any changes are added to the main.

**Comment by angelotheman** [comment]
Changes have been made, you can review and then accept so that we can merge with the main.

**Comment by Benobbi** [comment]
ok, lemme get that done

**Pull request merged**
